### ISSUE TITLE
[FIXED] mysql-client was renamed

### ISSUE THREAD

**Issue by j2l** [drupol/backdrop-docker#2]
Working Dockerfile:
...
RUN apt-get update
RUN sleep 10
RUN apt-get install -y default-mysql-client unzip curl sqlite3 git
...

**Comment by drupol** [comment]
?

**Comment by j2l** [comment]
Your Dockerfile is not working any more and I opened a ticket about that, and found a fix (default-mysql-client), so I closed it.
sleep 10 is not necessary

**Comment by drupol** [comment]
I will try to fix it.

In the meantime, you can provide a pull request with your changes, that would be very much appreciated!

**Comment by j2l** [comment]
PR done :)

**Comment by j2l** [comment]
BTW, a global update would be great!
